"""Thin per-backend launchers (task book section 7.2).

A launcher only selects the Python runtime: it execs the ``mliport`` console
script that lives in the backend's own virtual environment.  It must never
set ``CUDA_VISIBLE_DEVICES`` or change model defaults, dtype or scientific
configuration.
"""

from __future__ import annotations

import os
import stat
from pathlib import Path

from .compatibility import BACKENDS, BackendSpec

LAUNCHER_DIR = "bin"


def launcher_name(backend: BackendSpec) -> str:
    return f"mliport-{backend.engine}"


def posix_launcher_script(backend: BackendSpec) -> str:
    """POSIX ``sh`` launcher that execs the backend environment's CLI."""
    return (
        "#!/bin/sh\n"
        f"# Generated by mliport: run the mliport CLI from the "
        f"{backend.label} environment.\n"
        "# This wrapper only selects the Python runtime. It never changes\n"
        "# CUDA_VISIBLE_DEVICES, model selection, dtype or scientific\n"
        "# configuration.\n"
        'here=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)\n'
        f'exec "$here/../{backend.venv_name}/bin/mliport" "$@"\n'
    )


def windows_launcher_script(backend: BackendSpec) -> str:
    """Windows ``.cmd`` launcher for the backend environment's CLI."""
    return (
        "@echo off\n"
        f"rem Generated by mliport: run the mliport CLI from the "
        f"{backend.label} environment.\n"
        "rem This wrapper only selects the Python runtime.\n"
        f'"%~dp0..\\{backend.venv_name}\\Scripts\\mliport.exe" %*\n'
    )


def launcher_path(engine: str, base_dir: str | Path) -> Path:
    return Path(base_dir) / LAUNCHER_DIR / f"mliport-{engine}"


def create_launcher(backend: BackendSpec, base_dir: str | Path) -> Path:
    """Write the launcher(s) for one backend and return the POSIX path."""
    directory = Path(base_dir) / LAUNCHER_DIR
    directory.mkdir(parents=True, exist_ok=True)
    posix = directory / launcher_name(backend)
    posix.write_text(posix_launcher_script(backend), encoding="utf-8")
    posix.chmod(posix.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    if os.name == "nt":
        cmd = directory / f"{launcher_name(backend)}.cmd"
        cmd.write_text(windows_launcher_script(backend), encoding="utf-8")
    return posix


def create_launchers(engines: list[str], base_dir: str | Path) -> list[Path]:
    """Create launchers for every requested engine (registry-validated)."""
    created: list[Path] = []
    for engine in engines:
        key = str(engine).strip().lower()
        if key not in BACKENDS:
            raise ValueError(
                f"Unknown engine {engine!r}; choose from {', '.join(BACKENDS)}"
            )
        created.append(create_launcher(BACKENDS[key], base_dir))
    return created


__all__ = [
    "LAUNCHER_DIR",
    "create_launcher",
    "create_launchers",
    "launcher_name",
    "launcher_path",
    "posix_launcher_script",
    "windows_launcher_script",
]
